stages:          # List of stages for jobs, and their order of execution
  - build
  - release
  - deploy

variables:
  REGISTRY_USER: "macmiranda"
  REGISTRY_HOST: "quay.io"
  REGISTRY_BASEURL: "${REGISTRY_HOST}/${REGISTRY_USER}/"

build-job:       # This job runs in the build stage, which runs first.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
  # if not a tag build, use 'latest'
    - |
      [ ! -z ${CI_COMMIT_TAG} ] && TAG=":${CI_COMMIT_TAG}" || TAG=""
    - docker build --pull -t "${REGISTRY_BASEURL}${CI_PROJECT_NAME}${TAG}" 1/

release-job:   # This job runs in the release stage.
  image: docker:latest
  stage: release 
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_SECRET} ${REGISTRY_HOST}
  script:
    - |
      [ ! -z ${CI_COMMIT_TAG} ] && TAG=":${CI_COMMIT_TAG}" || TAG=""
    - echo "Releasing container image to registry"
    - docker push "${REGISTRY_BASEURL}${CI_PROJECT_NAME}${TAG}"

deploy-job:      # This job runs in the deploy stage.
  image: dtzar/helm-kubectl:latest # assuming K8s cluster version is either 1.19.x, 1.20.x or 1.21.x
  stage: deploy 
  script:
    - echo "Deploying application to K8s..."
    - mkdir $HOME/.kube
    - echo ${KUBECONFIG_SECRET} > $HOME/.kube/config
    - kubectl apply -f 2/litecoin-svc-sts.yaml && echo "Application successfully deployed."